### ISSUE TITLE
[RRF3 3.01-beta3 or earlier] Filament profile issues I found using a ToolChanger

### ISSUE THREAD

**Issue by Nibbels** [Duet3D/RepRapFirmware#352]
Board: Duet WiFi 1.02 or later + DueX5
Firmware: RepRapFirmware for Duet 2 WiFi/Ethernet 3.01-beta3 (2020-01-29b1)
Duet WiFi Server Version: 1.23

I use a duet2 + duex5 to drive a E3D toolchanger and want to follow the absolutly great idea of detaching the filament specific properties from my slicer. Thus I added a config in "Filaments" within the duet web UI.

1) I am still digging myself into the duet firmware and I am no expert yet. But here is some unnecessary behaviour (i think):
![Screenshot_2](https://user-images.githubusercontent.com/3265671/73612172-8936fc00-45e9-11ea-94b5-dde1456d2bc2.jpg)
Why should I not be able to assign one filament configuration to two tools?
  In my case I added a PETG configuration which can be totally valid for blue and green PETG.

And this hack seems to work?
![Screenshot_14](https://user-images.githubusercontent.com/3265671/73612814-6e678600-45ef-11ea-86b4-98955d16fa36.jpg)
I just added a space to the filaments folder name and it worked.
![Screenshot_15](https://user-images.githubusercontent.com/3265671/73612825-8b03be00-45ef-11ea-88d5-2784a5e4b5a7.jpg)
(EDIT:But this makes weird behaviour when swithing tools)

2) When I switch the filament-configuration in the web UI using this linkbutton
![Screenshot_4](https://user-images.githubusercontent.com/3265671/73612232-4e819380-45ea-11ea-9197-97dec31f336c.jpg)
then the printer always selects/grabs the tool if the printer is homed.
Andelse it **always** only **raises temperatures to active state if the printer is unhomed.**

But what I actually thought that would happen when choosing another filament type is that I just select the right filament for future M703 activation. No tools selection, no heatup. I want to leave the tools in state "off"/untouched.
(As a toolchanger owner I want set the filament type prior to printing and prior to homing, this stratey looks very comfortable to me)

If I manually grab a tool via console T1. And then send M701 S"285 PETG" then the behaviour is what I expected. A M703 afterwards loads the temperatures. So it is a strange behaviour of the web UI I think.
Do I get the theory of use wrong here?

3) If I want to download a Profile:
![Screenshot_5](https://user-images.githubusercontent.com/3265671/73612416-e469ee00-45eb-11ea-866f-f52bec55803b.jpg)

![Screenshot_6](https://user-images.githubusercontent.com/3265671/73612421-edf35600-45eb-11ea-9b18-98fc6a187ac2.jpg)

![Screenshot_7](https://user-images.githubusercontent.com/3265671/73612428-ffd4f900-45eb-11ea-9506-2f234b5c4bd9.jpg)
load.g and unload.g are empty.
Sometimes I get a download but it only contains the empty files.
![Screenshot_12](https://user-images.githubusercontent.com/3265671/73612508-b933ce80-45ec-11ea-80dc-d7781e8ae7c0.jpg)

When I put some comment into load.g then the error refers to the load.g
![Screenshot_9](https://user-images.githubusercontent.com/3265671/73612459-4165a400-45ec-11ea-8720-e5025889c26b.jpg)
![Screenshot_8](https://user-images.githubusercontent.com/3265671/73612456-3dd21d00-45ec-11ea-9f12-bd972f3b961d.jpg)

The download of the files directly is possible.
![Screenshot_10](https://user-images.githubusercontent.com/3265671/73612486-7b36aa80-45ec-11ea-90b5-20dfbe6a9799.jpg)
![Screenshot_11](https://user-images.githubusercontent.com/3265671/73612488-84277c00-45ec-11ea-82a8-59a3ccb6de0d.jpg)
![Screenshot_13](https://user-images.githubusercontent.com/3265671/73612527-d9638d80-45ec-11ea-89f0-45023b859d4b.jpg)

**Comment by cdedwards** [comment]
btw the JSON error when downloading a filament type, is actually an error from the web UI. This has been fixed in a very recent version of the web interface

**Comment by T3P3** [comment]
If these issues persist, please open a forum thread to discuss them.
